# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Install libgomp1
RUN apt-get update && apt-get install -y libgomp1

# Set the working directory in the container
WORKDIR /backend

# Copy the current directory contents into the container at /backend
COPY . /backend

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir --timeout=120 --retries=5 -r requirements.txt

# Make port 5001 available to the world outside this container
EXPOSE 5001

# Set the Python path
ENV PYTHONPATH=/backend

# Run main.py when the container launches
CMD ["python", "main.py"]